config/routes.rb
Rails.application.routes.draw do


    #ゲストログインのルーティング
    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    end

  scope module: :public do

    root to: 'homes#top'
    get 'homes/about' => 'homes#about',as: 'about'

    devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
    }

    resources :users, only: [:edit, :show, :index, :update] do
      get 'favorites' => 'users#favorites'
      resource :relationships, only: [:create, :destroy]
      get 'followinds' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts, only: [:edit, :show, :index, :create,:destroy,:update] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }
    root to: 'homes#top'

    resources :users, only: [:index, :show, :destroy]
    resources :posts, only: [:show, :destroy, :index]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    get 'search' => "searches#search"
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :post_image

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :post_comments

  validates :title, presence: true
  validates :sentence, presence: true

  def get_post_image(width,height)
    unless post_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      post_image.attach(io: File.open(file_path),filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    post_image.variant(resize_to_limit: [width,height]).processed
  end


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(search,word)
    if search == "perfect_match"
      Post.where("title LIKE?", "#{word}").or(Post.where("sentence LIKE?", "#{word}"))
      #.where("sentence LIKE?", "#{word}")
    elsif search == "forward_match"
      Post.where("title LIKE?", "#{word}%").or(Post.where("sentence LIKE?", "#{word}%"))
    elsif search == "backward_match"
      Post.where("title LIKE?", "%#{word}").or(Post.where("sentence LIKE?", "%#{word}"))
    elsif search == "partial_match"
      Post.where("title LIKE?", "%#{word}%").or(Post.where("sentence LIKE?", "%#{word}%"))
    else
      Post.all
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    pp params[:id]
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <h1>投稿一覧画面</h1>
    </div>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>タイトル</th>
          <th>説明</th>
          <th></th>
        </tr>
      </thead>
      <% @posts.each do |post| %>
      <tbody>
        <tr>
          <td><%= image_tag post.get_post_image(100,100) %></td>
          <td>
            <%= link_to admin_post_path(post) do %>
              <h2><%= post.title %></h2>
            <% end %>
          </td>
          <td><%= post.sentence %></td>
          <td><%= link_to "#{post.post_comments.count}コメント", admin_post_path(post) %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
        <h1>投稿詳細画面</h1>
  </div>
  <div class="row">
        <table class="table table-hover table-inverse">
                <tr>
                  <th><%= image_tag @post.get_post_image(100,100) %></th>
                  <th>title</th>
                  <th><%= @post.title %></th>
                </tr>
                <tr>
                  <th></th>
                  <th>Sentence</th>
                  <th><%= @post.sentence %></th>
                </tr>
        </table>
        <%= link_to "削除する", admin_post_path(@post), method: :delete %>
    </div>
</div>