config/routes.rb
Rails.application.routes.draw do


    #ゲストログインのルーティング
    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    end

  scope module: :public do

    root to: 'homes#top'
    get 'homes/about' => 'homes#about',as: 'about'

    devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
    }

    resources :users, only: [:edit, :show, :index, :update] do
      get 'favorites' => 'users#favorites'
      resource :relationships, only: [:create, :destroy]
      get 'followinds' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts, only: [:edit, :show, :index, :create,:destroy,:update] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }
    root to: 'homes#top'

    resources :users, only: [:index, :show, :destroy]
    resources :posts, only: [:show, :destroy, :index]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    get 'search' => "searches#search"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  #フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  #一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image


  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path),filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width,height]).processed
  end



  #followしたとき
  def follow(user_id)
   relationships.create(followed_id: user_id)
  end

  #followを外すとき
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  #followしているかを判定
  def following?(user)
    followings.include?(user)
  end

  def self.looks(search,word)
    if search == "perfect_match"
      User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      User.where("name LIKE?", "%#{word}%")
    else
      User.all
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'サンプル'
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users= User.all
  end

  def show
    @user=User.find(params[:id])
  end

  def destroy
    @user=User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <h1>会員一覧画面</h1>
    </div>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th><h2>name</h2></th>
          <th><h2>introduce</h2></th>
        </tr>
      </thead>
        <% @users.each do |user|%>
          <tbody>
            <tr>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
              <td>
                <%= link_to admin_user_path(user) do %>
                  <h4><%= user.name %></h4>
                <% end %>
              </td>
              <td><%= user.introduce %></td>
              <td><%= link_to "削除する", admin_user_path(user), method: :delete %></td>
            </tr>
          </tbody>
        <% end %>
    </table>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <h1>会員詳細画面</h1>
    </div>
    <table>
      <thead>
        <tr>
          <th></th>
          <th>ニックネーム</th>
          <th>自己紹介</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th><%=image_tag @user.get_profile_image(100,100) %></th>
          <th><%= @user.name %></th>
          <th><%= @user.introduce %></th>
          <th><%= link_to "削除する", admin_user_path(@user), method: :delete %></th>
        </tr>
      </tbody>
    </table>
  </div>
</div>