config/routes.rb
Rails.application.routes.draw do


    #ゲストログインのルーティング
    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    end

  scope module: :public do

    root to: 'homes#top'
    get 'homes/about' => 'homes#about',as: 'about'

    devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
    }

    resources :users, only: [:edit, :show, :index, :update] do
      get 'favorites' => 'users#favorites'
      resource :relationships, only: [:create, :destroy]
      get 'followinds' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts, only: [:edit, :show, :index, :create,:destroy,:update] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }
    root to: 'homes#top'

    resources :users, only: [:index, :show, :destroy]
    resources :posts, only: [:show, :destroy, :index]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    get 'search' => "searches#search"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
 belongs_to :user
 belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :post_image

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :post_comments

  validates :title, presence: true
  validates :sentence, presence: true

  def get_post_image(width,height)
    unless post_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      post_image.attach(io: File.open(file_path),filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    post_image.variant(resize_to_limit: [width,height]).processed
  end


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(search,word)
    if search == "perfect_match"
      Post.where("title LIKE?", "#{word}").or(Post.where("sentence LIKE?", "#{word}"))
      #.where("sentence LIKE?", "#{word}")
    elsif search == "forward_match"
      Post.where("title LIKE?", "#{word}%").or(Post.where("sentence LIKE?", "#{word}%"))
    elsif search == "backward_match"
      Post.where("title LIKE?", "%#{word}").or(Post.where("sentence LIKE?", "%#{word}"))
    elsif search == "partial_match"
      Post.where("title LIKE?", "%#{word}%").or(Post.where("sentence LIKE?", "%#{word}%"))
    else
      Post.all
    end
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  # class_name: "User"でUserモデルを参照
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  #フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  #一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image


  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path),filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width,height]).processed
  end



  #followしたとき
  def follow(user_id)
   relationships.create(followed_id: user_id)
  end

  #followを外すとき
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  #followしているかを判定
  def following?(user)
    followings.include?(user)
  end

  def self.looks(search,word)
    if search == "perfect_match"
      User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      User.where("name LIKE?", "%#{word}%")
    else
      User.all
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'サンプル'
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: post.id)
    favorite.post_id = post.id
    favorite.save
    redirect_to request.referer
  end

  def destroy
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: post.id)
    favorite.post_id = post.id
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comments_params)
    comment.post_id = post.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    post = Post.find(params[:post_id])
    comment = cuurennt_user.post_comments.find_by(params[:id])
    comment.post_id = post.id
    comment.destroy
    redirect_to request.referer
  end
  
  
  private
  
  def post_comments_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
      render "/public/users/index"
    else
      @posts = Post.looks(params[:search], params[:word])
      @post = Post.new
      render "/public/posts/index"
    end
    
  end



end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
  <div class="justify-content-end d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <!--<%#= link_to "ecohack" root_path %>-->
    <nav>
      <% if user_signed_in? %>
        ようこそ<%= current_user.name %>さん
        <%= link_to "Home", root_path, class: "btn btn-outline-success" %>
        <%= link_to "Users", users_path, class: "btn btn-outline-success" %>
        <%= link_to "Hacks", posts_path, class: "btn btn-outline-success" %>
        <%= link_to "ログアウト", destroy_user_session_path,method: :delete, class: "btn btn-outline-success" %>
      <% elsif admin_admin_signed_in? %>
        <%= link_to "Users", admin_users_path, class: "btn btn-outline-success" %>
        <%= link_to "Hacks", admin_posts_path, class: "btn btn-outline-success" %>
        <%= link_to "ログアウト", destroy_admin_admin_session_path, method: :delete, class: "btn btn-outline-success" %>
      <% else %>
        <% if current_page?(new_admin_admin_session_path) %>
          <%= link_to "ログイン", new_admin_admin_session_path, class: "btn btn-outline-success" %>
        <% else %>
          <%= link_to "Home", root_path, class: "btn btn-outline-success" %>
          <%= link_to "About", about_path, class: "btn btn-outline-success" %>
          <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-success" %>
          <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-success" %>
          <%= link_to "ゲストログイン", users_guest_sign_in_path,method: :post, class: "btn btn-outline-success" %>
        <% end %>
      <% end %>
    </nav>
    <%= render 'layouts/search' %>
  </div>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Hacks']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward_match"],["後方一致","backward_match"],["部分一致","partial_match"]])%>
      <%= f.submit "検索", class: "btn btn-primary"%>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecohack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <%= yield %>
    <footer style="height: 50px; width: 100%; position: absolute;　bottom: 0; "></footer>
  </body>
</html>

app/views/layouts/search_result.html.erb
<h2>Results index</h2>

<table class="table table-hover table-inverse">
  <% if @range == "User" %>
    <tbody>
      <%= @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <tbody>
      <% @hacks.each do |hack| %>
        <tr>
          <td><%= hack.title %></td>
          <td><%= hack.sentence %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>